### ISSUE TITLE
Experiment/implement ML workflow using TensorFlow / DeepLab

### ISSUE THREAD

**Issue by jjmata** [splashblot/dronedb#10]
Feel free to edit this first comment to specify your goals for this milestone, @ivanprado.

**Comment by ivanprado** [comment]
Two main ideas here:
- Using DeepLab to segment lettuces in (lettuces/holes/rest). Tasks:
  1. Use current lettuces implementation to generate a segmentation that would simplify the labeling for NN training. (@ivanprado)
  1. Generate a human verified labeled dataset
  1. Train deeplab and evaluate

First task is for @ivanprado and ii and iii can be done by @amlarraz or @ivanprado depending on workload.

**Comment by amlarraz** [comment]
Perfect, maybe the point 1 is the first step to generaré our own labels tool for image segmentation, with this idea I'll tell you everything I think during the labeling to improve the tool @ivanprado

**Comment by jjmata** [comment]
Taking off milestone plan, given lowered priority.

**Comment by ivanprado** [comment]
Closing. At that moment is it not clear if image segmentation will be a priority for fastraster. Integrated object detection/segmentation has been achieved with autofaster project.
