### ISSUE TITLE
Why the hell redis viz are not being invalidated on changes at beta?

### ISSUE THREAD

**Issue by ivanprado** [splashblot/dronedb#108]
It doesn't affect production, but affects beta and is annoying as we cannot assure deployment to prod is going to work by looking at beta. 

More on the causes of that issue can be seen here: https://github.com/splashblot/dronedb/issues/89

Investigate why this is happening and try to solve it.

**Comment by apercas** [comment]
Done here: https://github.com/splashblot/docker-dronedb/commit/eb526b3f4bfcfdb9f02ee4456269d29fce971940#diff-334afc6ebb93c2d6bf1ad5d206ba35c4

The domain wasn't well formed `.DOMAIN`, that little dot. Also, it was already defined in a previous line.
