### ISSUE TITLE
April 17 Carto Rebase

### ISSUE THREAD

**Issue by apercas** [splashblot/dronedb#14]
(re-written comment by @jjmata) Every month we should:

  - [x] Fast-forward the master branch to pick up latest changes
  - [x] Read [NEWS.md](https://github.com/CartoDB/cartodb/blob/master/NEWS.md) in all relevant repos ([here](https://github.com/CartoDB/cartodb.js/blob/develop/NEWS.md) and [here](https://github.com/CartoDB/crankshaft/blob/develop/NEWS.md) and [here](https://github.com/CartoDB/Windshaft-cartodb/blob/master/NEWS.md) and [here](https://github.com/CartoDB/CartoDB-SQL-API/blob/master/NEWS.md) as well ... probably more) and adjust as necessary
  - [ ] Pick up any necessary changes to config files ([app_config.yml](https://github.com/cartodb/cartodb/blob/master/config/app_config.yml.sample) and [here](https://github.com/CartoDB/CartoDB-SQL-API/tree/master/config/environments) and [here](https://github.com/CartoDB/Windshaft-cartodb/tree/master/config/environments) as well)
  - [x] Rebase the [tileo branch](https://github.com/splashblot/dronedb/tree/tileo)
  - [ ] Rebase any other bits that we are working on but have not made the [tileo branch](https://github.com/splashblot/dronedb/tree/tileo) yet ([tileo-devops](https://github.com/splashblot/dronedb/tree/tileo-devops) tends to have stuff "in progress" that hasn't been merged to [tileo](https://github.com/splashblot/dronedb/tree/tileo) yet)
  - [x] Deploy the sucker to `alpha.tileo.co` and test some of the sample data visualizations! ✌️ 
  - [ ] Promote "the build" to `beta.tileo.co` (when that exists 😈)

April-specific tasks:

  - [x] Fix Node version for Windshaft-cartodb, see [here](https://github.com/CartoDB/Windshaft-cartodb/blob/master/NEWS.md#300)
  - [ ] Pick up dataservices configuration example, see [here](https://github.com/CartoDB/cartodb/commit/bdb202cfc53d50316698331bc37096617af8fe56)

**Comment by jjmata** [comment]
But the milestone specific comments would be lost.  I'd rather keep it like this.  Better to separate them.

**Comment by jjmata** [comment]
Starting this early in hopes of completing if before next milestone begins.  In general it would be a good idea to always start a new milestone with a fresh Carto rebase.

**Comment by jjmata** [comment]
Every month we should:

  - [ ] Fast-forward the master branch to pick up latest changes
  - [ ] Read [NEWS.md](https://github.com/CartoDB/cartodb/blob/master/NEWS.md) in all relevant repos ([here](https://github.com/CartoDB/cartodb.js/blob/develop/NEWS.md) and [here](https://github.com/CartoDB/crankshaft/blob/develop/NEWS.md) and [here](https://github.com/CartoDB/Windshaft-cartodb/blob/master/NEWS.md) and [here](https://github.com/CartoDB/CartoDB-SQL-API/blob/master/NEWS.md) as well ... probably more) and adjust as necessary
  - [ ] Pick up any necessary changes to config files ([app_config.yml](https://github.com/cartodb/cartodb/blob/master/config/app_config.yml.sample) and [here](https://github.com/CartoDB/CartoDB-SQL-API/tree/master/config/environments) and [here](https://github.com/CartoDB/Windshaft-cartodb/tree/master/config/environments) as well)
  - [ ] Rebase the [tileo branch](https://github.com/splashblot/dronedb/tree/tileo)
  - [ ] Rebase any other bits that we are working on but have not made the [tileo branch](https://github.com/splashblot/dronedb/tree/tileo) yet ([tileo-devops](https://github.com/splashblot/dronedb/tree/tileo-devops) tends to have stuff "in progress" that hasn't been merged to [tileo](https://github.com/splashblot/dronedb/tree/tileo) yet)
  - [ ] Deploy the sucker to `alpha.tileo.co` and test some of the sample data visualizations! ✌️ 
  - [ ] Promote "the build" to `beta.tileo.co` (when that exists 😈)

**Comment by jjmata** [comment]
Took care of the first couple of "mindless" tasks (rebase of `master` and `tileo` branches ...)  Testing and making other things work now.

**Comment by jjmata** [comment]
Rolled back to `v2.89.0` of Windshaft-cartodb to make things easier, but started working on a Docker image as well:

  * https://github.com/splashblot/docker-Windshaft-cartodb

**Comment by jjmata** [comment]
This is probably as far as I'll get into this for this milestone.  Closing and moving open sub-tasks to next month ...
