### ISSUE TITLE
Load Spanish Catastro WMS layers

### ISSUE THREAD

**Issue by apercas** [splashblot/dronedb#15]
### Context
Spanish government offers an WMS server that we should be able to read

 

### Source
Please check the following links

1. http://www.catastro.minhap.es/webinspire/index.html
2. http://www.catastro.minhap.gob.es/esp/wms.asp
3. http://www.catastro.minhap.es/webinspire/documentos/inspire-WMS.pdf
4. http://www.google-earth.es/foros.php?p=45329 

### Issues detected
They don't serve the map as a Web Map Tile Server hence Carto won't load it directly.

**Comment by jjmata** [comment]
It would be kind of cool if we could offer these as "Data Observatory" datasets, no?  That would mean probably having to import them on our own DB, I assume ...

Thoughts?

NB.  Not urgent ... not even sure it's worth tackling in May, but we can discuss when we finalize the Milestone plan.

**Comment by apercas** [comment]
Yeah, the only issue here is that they don't offer the maps as tiled data.
![image](https://cloud.githubusercontent.com/assets/704210/24469458/d4b53622-14bb-11e7-8304-c144cd22372b.png)

**Comment by jjmata** [comment]
We want the polygons, not the tiles, right?  😕

**Comment by apercas** [comment]
Yeah, which they serve over a WMS server but not tiled (WMST). We'll have to take a detour to get there.

**Comment by apercas** [comment]
**UPDATE**
---

I tried to get this running using a new instance of `createWMSLayer()` from `vis.map` with the expected 'URL error'.
The URL used as an example was `http://ovc.catastro.meh.es/cartografia/INSPIRE/spadgcwms.aspx?service=wms&request=getmap&format=image/jpeg&bbox=512300,4663000,512500,4663200&width=1000&height=1000&srs=epsg:23029&layers=cp.cadastralparcel` and some modifications of it after that. (Different sizes and bbox but same projection and layer.)

After this trying I created a blank Leaflet map and used the native [`L.Tilelayer` flavour for `WMS` maps](http://leafletjs.com/examples/wms/wms.html) and called the service with its own metadata (available [here](http://www.catastro.minhap.es/webinspire/index.html)). Again I checked that they don't server tiles and that Leaflet won't display the data directly from the service.

**Comment by jjmata** [comment]
Might make best sense to write a script that, when on-boarding a new company, queries the Catastro APIs to download the vectorial data related to their fields.  From that point on we serve them from our own servers (as part of our own _Data Observatory_?)

**Comment by apercas** [comment]
Closing, functionality added over XLS import
