### ISSUE TITLE
Prepare beta for Grupo G's

### ISSUE THREAD

**Issue by ivanprado** [splashblot/dronedb#18]
Prepare beta.tileo for being ready for the Grupo G's demo. Tasks:

- [x] Create an account on beta so that people from grupo G's can have access. Alternatively, we can just make the map public. 
- [x] Make available the basemap on beta using the NDVI GeoTiff that was provided. 
- [x] beta will need capability for deep zoom
- [ ] Re-brand email templates & Org pages
- [x] Make sure exports work again (see #5)
- [ ] (optional) Prepare some kind of interactivity over the map, so that when you select a region, it gives you the lettuces count. There are 5 subfields. Each point on the output GeoJson will have the field id as an attribute. 
- [ ] (optional) Include RGB basemap as well. 

Links to GeoTiffs:
- s3://tileo-datasets/grupo-gs/lettuces-under-cover/NVDI/NDVI1.tif
- s3://tileo-datasets/grupo-gs/lettuces-under-cover/RGB/RGB.tif

**Comment by jjmata** [comment]
At least we have https://beta.tileo.co up now ... ;-)

**Comment by jjmata** [comment]
I just uploaded (on alpha's `dev` user for testing/development) the two GeoTIFFs referenced above:

  * [NDVI layer](https://alpha.tileo.co/user/dev/builder/3d3e9bb4-18bf-11e7-822d-0242ac120006)
  * [RGB layer](https://alpha.tileo.co/user/dev/builder/440be876-18cd-11e7-9217-0242ac120006)

They are useless maps right now since we don't have the tilesets yet, but it might be a good idea to render them as per my comments in #7.  Thoughts @apercas?

**Comment by jjmata** [comment]
Update: zoom level works, beta SSL is working, and @apercas is debugging the points issue.

Working on the ability to auto-tile all raster uploads, which will give us basemaps / raster layers for free with a simple drag & drop.  Good progress here https://github.com/splashblot/dronedb/tree/tileo-feature/tiff-tiler and hope to have it finished today while I listen to conference people talk. 😮

**Comment by jjmata** [comment]
Fixed the point limit issue (#20) just now!

**Comment by ivanprado** [comment]
The almost final GeoJSON file is finished. It failed to upload to alpha. From my side the job is done. The file is attached so that it can be uploaded to the final account/map with the corresponding NDVI raster. 

[lettuces-under-cover-local-maximas-10240-2017-04-11-2.xls.output.geojson.zip](https://github.com/splashblot/dronedb/files/913877/lettuces-under-cover-local-maximas-10240-2017-04-11-2.xls.output.geojson.zip)

**Comment by ivanprado** [comment]
New GeoJSON that is properly aligned and where outliers were removed. 
[lettuces-under-cover-local-maximas-10240-2017-04-12.xls.output.geojson.zip](https://github.com/splashblot/dronedb/files/916559/lettuces-under-cover-local-maximas-10240-2017-04-12.xls.output.geojson.zip)

**Comment by jjmata** [comment]
Added "clean" TIFFs here:

- s3://tileo-datasets/grupo-gs/lettuces-under-cover/NVDI/NDVI1-clean.tif
- s3://tileo-datasets/grupo-gs/lettuces-under-cover/RGB/RGB-clean.tif

MapTiler is giving me trouble, so I'll try to run them on `gdal2tiles.py` soon.

**Comment by jjmata** [comment]
We have a script to create accounts for them [here](https://github.com/splashblot/tileo-sampledata/tree/master/gs-fresh), and everything else we wanted to do was mostly done.  Closing and moving the one remaining item (template updates) to the June rebase.
