### ISSUE TITLE
Hand-craft visualization of lettuce datasets

### ISSUE THREAD

**Issue by jjmata** [splashblot/dronedb#2]
The GeoJSON datasets are pretty much ready: [one](https://alpha.tileo.co/user/dev/dataset/lettuces_full_tif_holes), [two](https://alpha.tileo.co/user/dev/dataset/lettuces_full_tif_lanes), [three](https://alpha.tileo.co/user/dev/dataset/lettuces_fields) (we have something we can work with already, but @ivanprado is going to re-run the _holes_ one to get us better accuracy), so the idea is to:

- [ ] complete the "multiple basemap" trick from #1
- [x] import three (more?) layers: lanes, holes, fields
- [x] add a widget that calculates de estimated number of lettuces per "field"
- [x] improvise and add a few other widgets
- [ ] improvise and add a heatmap of holes

Did I miss anything as discussed, @apercas or @ivanprado?

**Comment by apercas** [comment]
I didn't want to check them out but we have already imported the lanes, holes and fields dataset and we can add a heatmap with the holes with no effort.

The widget issue that is driving me crazy in detail is:
_How to reproduce_:
-Both locally or on alpha: Add a widget (whichever you like)
-Try to display it
_Cause_:
-Failing while routing (for some reason the `http://tileo.localhost/` becomes `http://dev.localhost.lan:8181`)
_Where to see it_:
-Check the right hand column
_Status_:
-I first checked the `app_config` YAML file so it matches the preferred route. It didn't change anything at all (meaning: it changes the regular route but for this bug it did't apply).
-I started debugging using Chrome DevTools adding a breakpoint in the XHR and then scaled up until I spotted URL change itself on `model-updater.js` L166:
```
var dataviewMetadata = windshaftMap.getDataviewMetadata(dataviewModel.get('id'));
```
-I checked the `Windshaft` config and the output there and both are correct
-I couldn't test it but my guess is that the content of each item of the `DataView` collection is wrong (meaning, poor URL) from the its creation.

**Comment by jjmata** [comment]
I found the reason for the widget issue*, it's a missing configuration value as we suspected (a new one that we are missing) on the Windshaft side.  It dates back to November (so recent in the grand scheme of things), here is the commit:

  * https://github.com/CartoDB/Windshaft-cartodb/commit/488698d5e2df05aea5a440c47014dcd49fa86567

And the historical background directly from @rochoa's mouth :-)

  * https://github.com/CartoDB/Windshaft-cartodb/issues/493
  * https://github.com/CartoDB/Windshaft-cartodb/pull/594

(*) I didn't step into it via debugger, but I believe the fallback URL was being assembled [here](https://github.com/CartoDB/Windshaft-cartodb/blob/master/lib/cartodb/controllers/map.js#L469).

**Comment by jjmata** [comment]
This was accomplished and demo'ed to Grupo Gs a few days back.  Closing.
