### ISSUE TITLE
Create landing page for Tileo.[co|es]

### ISSUE THREAD

**Issue by jjmata** [splashblot/dronedb#21]
Single-page, single call to action.  Keep it simple stupid (KISS) and collect people's email address in exchange for a "sneak peak" of our beta.  Implement "scarcity" system for people 

Include a teaser link to a public viz of the lettuce dataset (get client to agree first!)

A few things that maybe go without saying:

  - [ ] Make sure it works on mobile (phone & tablet)
  - [x] Hook it up with Segment.io
  - [x] Hook it up with Google Analytics (`UA-97377616-3`)
  - [x] Enable with Mailgun
  - [x] Hook it up with Hubspot
  - [x] Turn off Hubspot on non-website pages
  - [ ] Enable HTTPS
  - [ ] Add `secrets` to `docker-compose.yml` file
  - [ ] Finalize instance to host
  - [ ] (optional now, required later) A/B test CTA & tag line

Second push:

  - [ ] Update text copy to address FENAVIN audience (not Tarugos!)
  - [ ] Create Spanish version
  - [ ] (optional) Page specific for wine?

**Comment by jjmata** [comment]
It's not a coincidence that this tab was open in one of my browsers the last few days:

  * https://blog.chartmogul.com/saas-landing-pages-2017-analysis/

/cc @apercas @ivanprado @amlarraz in case you want to comment / add your 2 cents ...

**Comment by apercas** [comment]
IMO, if we're going static, let's use the (basic) proper tools https://pages.github.com/ We all know how Github works, so their own pages with a redirect should be more than enough.

**Comment by jjmata** [comment]
“... good artists borrow, great artists steal ...”  Did you take a look at the ChartMogul article?  Let's discuss after we have beta ready for the new demo.

**Comment by apercas** [comment]
I did! And I agree with the fewer CTA policy. Actually in our case I think we only need two of them: 'See a demo' (map with a state of the art overfitted presentation) and 'Contact us now' with a form/email.

Then a bunch of paragraphs with the how/where (worldwide)/who(?) plus a twitter link to keep the conversation up.

**Comment by jjmata** [comment]
Thanks for all the work on this today, @apercas and @ivanprado.

I've made a few edits on the sandbox and now have a Dockerized site up on AWS that we can move everything to.  Can you take care of that part, @apercas?  Just visit http://tileo.co and use the same credentials as you have put on Meldium today.

In general I've simplified things (taken section titles out, left just one picture in the carousel and made the main panel shorter to try and get everything to fit above the fold ...)  I feel we still need to work on it some more tomorrow, so I've asked that the link go out Friday.

Added a couple more TODOs like adding the `secrets` to our compose file, and finalizing host to run this.

**Comment by jjmata** [comment]
General thoughts on things that I'm still trying to fix/could use your help & thoughts:

  * Solutions don't render well in mobile, they actually render very poorly.
  * Solutions are sized by the text that follows them, should make them size independent of them.
  * Font family / size / weight of "Tileo" and "Artificial Intelligence for Precision Agriculture" feels weak.
  * I might have removed too much, in my search for "minimalism"

Thoughts on copy?  I went the minimalist route since the less we say the more we leave to the imagination.  Let me know if that was too much of a "cut" ...

**Comment by ivanprado** [comment]
Thoughts about new copy:

> We automate data collection using drones, GoPro cameras, satellites, you name it!
> We use convolutional neural networks, trained to help with real-world problems like yield estimation, crop quality and field irregularity.
> We offer a best-in-class visualization workbench that helps your team spot trends and stay organized.

- "automate data collection", "convolutional neural networks", etc... all of them are pretty technical terms. Good for impressing techies coming to TarugoConf, but no so good for people coming Fenavin, where our real clients can be. 
- I would replace the repeated use of "we" as I think give some sensation of amateuris. 

Thoughts on minimalism/design:

- The page gives me the sensation doesn't fit together. It looks too small in my computer. It doesn't give me a cool sensation. On mobile doesn't work as you told because images are cut. An in general I would say that the page "no respira". Everything is too packed. 

My cents:

One of your focus is to have the main message fit above the fold. Which makes sense to me. But I think the solution is not making everything smaller or more packed. I would say page should adapt to the size. I'll try to explain with some examples. Look to [clearbit](https://clearbit.com/) page. On computer browsers/tablets main message fits on the screen. But on mobiles, page version is simplified. More examples: [Workable](https://www.workable.com/), [Wix](http://www.wix.com/). I just got some of them from the [page you shared about landing pages](https://blog.chartmogul.com/saas-landing-pages-2017-analysis/).

**Comment by apercas** [comment]
It looks weirder now indeed. Let me try to fix the proportions.

**Comment by jjmata** [comment]
I will work on the final copy details tonight and remove the "we" indeed.  It was a brain-fart late last night in search of unnecessary consistency between those three paragraphs.

I agree 100% about audience, @ivanprado.  I plan on changing the overall audience/copy early next week after the first few "targuos" have seen the LP an we can move to our real target market.  OK?  Will also take their feedback into account.  We're not trying to sell to them ML workflows after all.

For now, I'm actually hearing good feedback from other entrepreneurs about the copy.  Which is a clear "kiss of death" as it should speak no to them, but to industrial food people.  The best comment so far was to take the "_help with real-world problems like yield estimation, crop quality and field irregularity_" and make that the tagline.  It's long, but probably better than what we have.

**Comment by jjmata** [comment]
As far as progress I made this morning, everything is ready for a `tileo.co` production push after @apercas is done with final touches on the sandbox.

I've installed a bunch of plugins, activated Hubspot and only a few details (Google Analytics, etc.) remain.  See [here](https://github.com/splashblot/tileo-site/commit/0348e1d34238f369b151d0dce68b8d8e65b5d94c).

I've left the WP instance in "maintenance mode" for now, to avoid further embarrassment.

**Comment by jjmata** [comment]
What, no updates? 😱 

I see a lot of stuff is already fixed over at http://tileo.co ... cool beans!

(taking over for a bit)

**Comment by jjmata** [comment]
Some fixes/changes:

  * Added Google Analytics (goes in footer)
  * Top image back to `50vh` height (takes up too much room above the fold otherwise at `70vh`)
  * Assets where still hosted at https://tileo.splashblot.com/wp-content/themes/tileo/img/field/ so moved them to Media Library (and re-compressed them to help slow download times, one was 4.4MB!)
  * Couple of small copy edits courtesy of the only native speaker in the team!
  * Replaced the `html5` favicon for our own
  * Pixel-fucked with the "O" animation

Back to @apercas in case he objects to any of my changes.  Tweet with link to our LP should go out around 11am Madrid time.

**Comment by apercas** [comment]
This link seems helpful for the copies https://medium.dave-bailey.com/the-magic-formula-to-describe-a-product-in-one-sentence-175ce38619c7

**Edit:** another summary of the CM article [here on Quora](https://www.quora.com/What-makes-a-great-SaaS-homepage).

**Comment by apercas** [comment]
Can we use the same SSL certification we have on alpha/beta here? And, are we supporting anything but English and Spanish? Maybe I can start testing multilingual plugins.

**Comment by jjmata** [comment]
My take is this: English as default for everything, and Spanish for landing pages and major areas only (index, etc.)

**Comment by jjmata** [comment]
As far as SSL goes, we can try to use the same SSL cert ... yes (using a wildcard one) but for now alpha/beta use Let'sEncrypt and it makes it hard.

**Comment by apercas** [comment]
Updated with skewed layout.

**Comment by jjmata** [comment]
Closing this (we had what we needed for the first iteration) and moving remaining items [here](https://github.com/splashblot/dronedb/issues/30).
