### ISSUE TITLE
Automatize training/inference with faster for new datasets

### ISSUE THREAD

**Issue by ivanprado** [splashblot/dronedb#29]
Now each time we want to add a new dataset to train faster we have to follow the steps described  [here](https://github.com/deboc/py-faster-rcnn/blob/master/help/Readme.md)

Create a set of scripts where that is automatized. These new set of scripts should be parametrized so that a set of labels to train should be provided. For example when provided `cat,dog,snake` the script will deal to train a model for three categories with the given names. 

Also inference scripts should be automatized. [infere.py](https://github.com/splashblot/py-faster-rcnn/blob/python3/tools/infer_mandarine.py) could be used as reference.

**Comment by ivanprado** [comment]
Pull request accepted. Could you add a section to README.md explaining the usage of the tool (probably with a simple example)?

**Comment by amlarraz** [comment]
Done! Everything merged in fastraster repo :)
