### ISSUE TITLE
Landing page for FENAVIN bug-fixing

### ISSUE THREAD

**Issue by ivanprado** [splashblot/dronedb#30]
**General:**

- [x] HubSpot in Spanish. 
- [x] Proper font/size relation between section titles and section content

**On desktop version:**

- [x] Three solutions bottom image alignment

**On mobile version:**

- [x] Remove titles slopes

**Comment by apercas** [comment]
Updated.

**Comment by jjmata** [comment]
Remaining from the original LP task:
  - [x] Create Spanish version - _@ivanprado completed it_
  - [ ] ~~Enable HTTPS~~
  - [ ] ~~Add `secrets` to `docker-compose.yml` file~~
  - [ ] ~~Finalize instance to host~~
  - [ ] ~~(optional now, required later) A/B test CTA & tag line~~

**Edit on 2017/06/30:** moved remaining items here: https://github.com/splashblot/dronedb/issues/42

**Comment by jjmata** [comment]
I turned off Hubspot's **Request Early Access** for now, not much value added by it from the current form.

**Comment by jjmata** [comment]
The remaining items here can be tackled later, so this can go back to the backlog as far as the intended milestone is concerned.  Removing it from Juno.

**Comment by jjmata** [comment]
Actually, let's create a new task.  I shouldn't have renamed this one in the first place.

**Comment by jjmata** [comment]
New task ( https://github.com/splashblot/dronedb/issues/42 ) is ready, so closing this.
