### ISSUE TITLE
Demo lechugas Murcia

### ISSUE THREAD

**Issue by jjmata** [splashblot/dronedb#32]
Needed by COB 6/13:

 - [x] GeoTIFF uploaded to `beta` ("el de siempre"), cropped to an optimal area 
 - [x] Run inference on that same crop
 - [x] Upload corresponding GeoJSON to `beta` _**EDIT** 21:30CET: after deploying `tileo-feature/raster-layer-builder` to `alpha`_
 - [x] Demo to Sergio or agree to somebody else demoing (Iván?)

**Comment by jjmata** [comment]
Assigning to @amlarraz to make the crop, over to @apercas for uploading / tiling / etc. to `beta.tileo.co`

**Comment by jjmata** [comment]
Full demo was not completed, leave open to debug GeoJSON import and finish up details so packaged demo can be ready.

**Comment by jjmata** [comment]
Yesterday I was able to upload all artifacts that were generated for this demo.  All issues had to do with import limits (file size) and not functionality/bugs.  I'm in the process of updating the `tileo-sampledata` repo so that our users don't hit these limits anymore.

The final idea here is to generate 3-5 visualizations that we can re-use going forward:
  - The ones for the original field where we used both OpenCV and a convnet to count and estimate radius.
  - The ones for the second field where the lettuces where covered and we used an NDVI raster.
  - The one for the UK field that had very poor resolution.
  - The one with the full scan that used a convnet and gave us upwards of 600k polygons.

Correct, @ivanprado?  Am I missing other possible visualizations?

**Comment by ivanprado** [comment]
Some notes for each visualization:
Vis 1: Both count and radius are OpenCV
Vis 2: Ok
Vis 3: I wouldn't keep that map, as quality is so poor that is not reasonable to keep it as demo. 
Vis 4: I wouldn't use that one as demo, as some parts of the dataset have non reasonable image quality. Instead I would use as demo the crop (already sent to you)

The 600k vis and UK vis could be interest to keep just for internal use.

**Comment by jjmata** [comment]
Interesting ... just uploaded `rg_lechugasgs_transparent_mosaic_group1.tif.detect.4x.json` and got this error in builder:

`rg_lechugasgs_transparent_mosaic_group1_tif_detect_4x: Postgis Plugin: server closed the connection unexpectedly	This probably means the server terminated abnormally	before or while processing the request.in executeQuery Full sql was: 'SELECT * FROM (SELECT * FROM pablo.rg_lechugasgs_transparent_mosaic_group1_tif_detect_4x) as cdbq LIMIT 0' encountered during parsing of layer '6c6d74d6-0680-4151-870f-2aca0a721259' in Layer`

Incidentally I've been having Postgres disconnects on the `tileo-smartrural` Swarm setup, so it could be related to that problem.

**Comment by jjmata** [comment]
The dataset above was just uploaded to a fresh DB instance at `smartrural.tileo.co` again, please take a look and let me know what visualizations you had in mind as per today's comments at the team meeting, @ivanprado:

  * https://smartrural.tileo.co/user/dev/builder/be3a5502-6061-11e7-8d91-02420a000103

**Comment by ivanprado** [comment]
Visualization seen. The requirements for final visualization are:
- [ ] Instead of loading the full field, just load the cropped section at file https://tileo.slack.com/files/ivan.prado/F60EA4JG6/lettuces-4x-crop.tar.gz . The file includes both the GeoJSON and the raster. 
- [ ]  Load raster file as basemap or as raster
- [ ] Load GeoJson
- [ ] Have support for depth zoom capabilities

Tell me when a deployment with that capabilities is ready. I can upload the data then.

**Comment by jjmata** [comment]
All of this functionality is now available / working on https://smartrural.tileo.co

We'll see who gets to it first!

**Comment by ivanprado** [comment]
On fruit-attraction demo account.
