### ISSUE TITLE
Demo environment for SmartRural

### ISSUE THREAD

**Issue by jjmata** [splashblot/dronedb#35]
Build a demo environment for SmartRural sales calls, base it on the dataset of their choice and achieve:

  * [ ] A more "agro look"
  * [ ] Spanish locale that is agriculture-specific ("parcelas", not "mapas")
  * [ ] Custom logo, avatars
  * [ ] Multiple users (both viewer and admin) under the `smartrural` organization
  * [ ] Raster as well as discrete data sets (should we include the "heladas" sample as GeoJSON?)
  * [ ] Working email notifications

Optional / future:
  * [ ] Sample data library datasets (temperature, sensors, etc.)
  * [ ] DNS subdomain
  * [ ] Mobile app for viewing and basic data input

**Comment by jjmata** [comment]
Giving over to @MariaCheca so she can decide how much to tackle this milestone.

**Comment by MariaCheca** [comment]
🌈

**Comment by jjmata** [comment]
We should split this work out into smaller / more digestible bits (week-long at most) so we can start putting them on the new kanban view.  It's also smarter project management when you divide an conquer in smaller increments, am-I-rite?

**Comment by MariaCheca** [comment]
Sure! Let me do it :)

**Comment by ivanprado** [comment]
Closing. Most of these tasks has been archived with Fruit-Attraction milestone.
