### ISSUE TITLE
Published maps not reendering vector data some times

### ISSUE THREAD

**Issue by ivanprado** [splashblot/dronedb#36]
After some time "Águilas under cover lettuces" public map doesn't show vector data. In order to get data back public map must be republished (updated). Wondering if that is happening when Carto is restarted.

**Comment by jjmata** [comment]
This is probably part of many of the fixes @apercas is making currently for the Pago datasets/viz work.  Care to comment, Adrián?  Want to just add that work here?  Or consider it a duplicate of another one?

**Comment by ivanprado** [comment]
Probably solved when enabled redis persistence, as I have not seen that behavior anymore. Closing.
