### ISSUE TITLE
Map view not working on Internet Explorer

### ISSUE THREAD

**Issue by ivanprado** [splashblot/dronedb#37]
That map view is not working under Internet Explorer. That explains the problems of Diego and Sergio. 

## Checked versions:

Explorer 11.1358.14.393.0.IC Update version 11.0.43
Explorer 11.0.9600.18376 Update version 11.0.33

## Example URLs tested not working:

https://beta.tileo.co/user/dev/builder/5ef6081c-b744-4094-891d-df8c2afb927a (The builder page)
https://beta.tileo.co/user/dev/builder/30416225-ebf8-43cb-9c50-3940b1b5272a/embed (Public map view)

**Comment by apercas** [comment]
Checking over Browserstack.

**Comment by apercas** [comment]
This has been solved on alpha.
In order to deploy the changes on beta we'll need to run:
```
$ cd /dronedb
# update the node modules library with the new cartodb.js codebase
$ npm update
# remove previous static files
$ rm -r /public/assets
# recreate those assets with the new files
$ grunt
```

Passing to @jjmata

**Comment by jjmata** [comment]
This was deployed to `beta` earlier today ... can you confirm it's fixed there now?

**Comment by apercas** [comment]
I checked over Browserstack on Windows 10/IE 11, Windows 8/IE 11 and Windows 7/IE 10. It's fixed. Although the rendering speed on IE10 (basemap + vectors + raster) is slow. Wouldn't cry about it, actually.

Closing.
