### ISSUE TITLE
Imposible to change Avatar

### ISSUE THREAD

**Issue by ivanprado** [splashblot/dronedb#39]
It is not possible to upload an Avatar.

**Comment by jjmata** [comment]
Pretty sure this has to do with the S3 assets issue, will triage today.

**Comment by jjmata** [comment]
Probably related to this "still in my local repo" change:

```
jjmata at rye in ~/src/docker-dronedb on master [!]
$ git diff
diff --git a/startup.sh b/startup.sh
index bc64fe2..9fd90a4 100755
--- a/startup.sh
+++ b/startup.sh
@@ -50,7 +50,9 @@ HUBSPOT_TOKEN=$(cat /run/secrets/HUBSPOT_TOKEN) \
   FS_ORG=$(cat /run/secrets/FS_ORG) \
   ROLLBAR_API_KEY=$(cat /run/secrets/ROLLBAR_API_KEY) \
   MAILGUN_POSTMASTER_PASSWORD=$(cat /run/secrets/MAILGUN_POSTMASTER_PASSWORD) \
-  envsubst '$HUBSPOT_TOKEN:$FS_ORG:$ROLLBAR_API_KEY:$MAILGUN_POSTMASTER_PASSWORD'\
+  AWS_S3_ACCESS_KEY_ID=$(cat /run/secrets/AWS_S3_ACCESS_KEY_ID) \
+  AWS_S3_SECRET_ACCESS_KEY=$(cat /run/secrets/AWS_S3_SECRET_ACCESS_KEY) \
+  envsubst '$HUBSPOT_TOKEN:$FS_ORG:$ROLLBAR_API_KEY:$MAILGUN_POSTMASTER_PASSWORD:$AWS_S3_ACCESS_KEY_ID:$AWS_S3_SECRET_ACCESS_KEY'\
   < /dronedb/config/app_config.yml.pre-secrets \
   > /dronedb/config/app_config.yml
```

**Comment by apercas** [comment]
Are we switching to gravitar or backing up to the AWS solution?

**Comment by jjmata** [comment]
Both should work (Gravatar and local/AWS).

**Comment by apercas** [comment]
**UPDATE**
After `puts`-ing from https://github.com/splashblot/dronedb/blob/tileo-june2017/app/models/asset.rb#L160 the values of `Cartodb.config[:aws]["s3"]` and `Cartodb.config[:assets]["s3_bucket_name"]` the results are:

```
dronedb_1     | {"access_key_id"=>"", "secret_access_key"=>""}
dronedb_1     | tileo-localhost-org-assets
```

So it can read the name of the bucket but not access key pair. Will update with more info when available.

**Comment by jjmata** [comment]
OK, mystery solved ... at some point in the last few days `envsubst` of the tokens started failing, so:

```
root@ec1871cc4cb7:/dronedb/config# diff app_config.yml app_config.yml.pre-secrets
248,249c248,249
<       access_key_id: ""
<       secret_access_key: ""
---
>       access_key_id: "$AWS_S3_ACCESS_KEY_ID"
>       secret_access_key: "$AWS_S3_SECRET_ACCESS_KEY"
686c686
<     password: ''
---
>     password: '$MAILGUN_POSTMASTER_PASSWORD'
704c704
<   rollbar_api_key: ''
---
>   rollbar_api_key: '$ROLLBAR_API_KEY'
706c706
<     org: ''
---
>     org: '$FS_ORG'
712c712
<       token: ''
---
>       token: '$HUBSPOT_TOKEN'
```

Those empty entries should have values in them!

This seem to be the offending error:

```
dronedb_1        | /opt/startup.sh: line 65:  : command not found
```

[Line 65](https://github.com/splashblot/docker-dronedb/blob/master/startup.sh#L65) takes care of the substitution.

**Comment by jjmata** [comment]
I'll finish this tomorrow, taking over here.

**Comment by apercas** [comment]
Hope this works! From my end: I directly added a brand new pair of access keys on [file_upload.rb](https://github.com/splashblot/dronedb/blob/tileo-june2017/app/helpers/file_upload.rb#L97) and the logs prompted the correct values (obviously) however I got the same 'no valid credentials' issue. Maybe I didn't grant proper access to that pair as my knowledge of AWS console is not strong.

**Comment by jjmata** [comment]
The S3 buckets piece is working now (see https://github.com/splashblot/dronedb/issues/12) and I can see the assets uploaded to the appropriate bucket, one of:

  * `tileo-development-assets`, or
  * `tileo-staging-assets`

But for some reason the UI doesn't reflect / update and start using the asset.  I believe we need to do some more configuration to start serving those assets, haven't found where.  Do you remember where this is done, @MariaCheca?

**Comment by jjmata** [comment]
I can confirm that the assets are (at least sometimes) coming from S3:

  * https://tileo-staging-assets.s3.amazonaws.com/staging/dev/assets/20170712152103pasted_image_at_2017_06_23_12_31_pm.png

That's the SmartRural logo that is currently working in prod.
