### ISSUE TITLE
Force zoom further 22

### ISSUE THREAD

**Issue by apercas** [splashblot/dronedb#4]
I just found this article http://wesmapping.com/blog/zoom-past-maximum-tile-level-with-leaflet/ and I guess it will be helpful to give it a try /cc @jjmata

**Comment by jjmata** [comment]
Indeed!  Nice find ...

There is a Spaniard in London who is a Leaflet-wiz ... we should ask him as well (and Santana as well, of course!)

**Comment by jjmata** [comment]
FYI, we mentioned this to @saleiva in person last week and he seemed to think it would be feasible.  We need to dig a little deeper, and might come up with questions then, Sergio!

**Comment by saleiva** [comment]
ok! :)

**Comment by apercas** [comment]
Update: Check commit 4ae3678bc5f7efd1f77b36e27262f4a8aaff2d07 and `git checkout` it to roughly try it out. Forced to level 50.

![image](https://cloud.githubusercontent.com/assets/704210/23904231/643d0fbe-08c7-11e7-99b1-ccf4f31422c8.png)
