### ISSUE TITLE
Move to ogr2ogr2.1

### ISSUE THREAD

**Issue by jjmata** [splashblot/dronedb#5]
Do you remember what was the reason for [upgrading](https://github.com/CartoDB/cartodb/commit/86ad756b12e479475ed8dee287c9f5acf8008380), @iriberri?  What breaks with the old one?

**Comment by iriberri** [comment]
Hey there! If I'm not wrong, besides from benefiting from several ogr2ogr bugfixes related to different data formats, the main reason was to be able to use the `PRELUDE_STATEMENTS` and `CLOSING_STATEMENTS` feature that allowed us to modify the `statement_timeout`: https://github.com/CartoDB/cartodb/blob/04998b0739050fce80c3c9adae271d0327beb8c5/services/importer/lib/importer/ogr2ogr.rb#L216-L217

Also see: https://github.com/CartoDB/cartodb/pull/6975

If I remember correctly, the old ogr2ogr version will just ignore the prelude/closing statements and it will not break, just raise some warnings at the import logs. Updating to ogr2ogr2.1 shouldn't break anything that was working before.

Hope this helps! Please let me know if you have any other questions!

**Comment by jjmata** [comment]
Thanks, @iriberri!  We'll [take a look](https://github.com/splashblot/docker-dronedb/blob/master/Dockerfile#L119) and maybe upgrade GDAL at the same time ... do you remember what version of GDAL was being used lately?

**Comment by jjmata** [comment]
Fixed in [a250ebd](https://github.com/splashblot/docker-dronedb/commit/a250ebdd37b6c50ff223f539686e6ec787585bb6) since it seemed to be affecting exports.

**Comment by jjmata** [comment]
Fixed in [a250ebd](https://github.com/splashblot/docker-dronedb/commit/a250ebdd37b6c50ff223f539686e6ec787585bb6) since it seemed to be affecting exports.
