### ISSUE TITLE
Fix org invitation flow with subdomains

### ISSUE THREAD

**Issue by MariaCheca** [splashblot/dronedb#55]
Related: https://github.com/splashblot/dronedb/issues/45

As part of the emails setup the invitation emails and the internal flow to allow invited users to sign up, it's needed to test and fix (if necessary) the sign up links sent in these emails.

**Comment by jjmata** [comment]
This is now working on "beta", and will be deployed after some testing (and fixes to templates that it exposes ...)  Can you take care of that last piece, @MariaCheca?

**Comment by jjmata** [comment]
This is now working on "beta", and will be deployed after some testing (and fixes to templates that it exposes ...)  Can you take care of that last piece, @MariaCheca?
