### ISSUE TITLE
More zoom levels in all basemaps

### ISSUE THREAD

**Issue by ivanprado** [splashblot/dronedb#65]
At the moment extended zoom levels only works on custom basemaps. Include them in all basemaps if possible by default.

**Comment by jjmata** [comment]
I believe this is not possible (or at least, not desirable) as the basemap dissapears if you go beyond the supported zoom level.  An easy way to test it if you desire is to update these values, @ivanprado:

https://github.com/splashblot/docker-dronedb/blob/master/config/app_config.yml.envsubst#L357

The file resides in `/dronedb/config` and you can let us know if they results are what you expect.

**Comment by ivanprado** [comment]
You are right. Max possible zoom level on provided basemaps are 20. So if you want more zoom level you must:
* Use custom color basemap
* Use your own custom basemap

I think it can be reasonable by now as:
* We need more zoom level if doing counting. But in this case we can use rasters, and rasters doesn't have zoom limitation at all. 
* The rest of the cases (like NDVI maps) probably we can live with zoom level 20.

In the future I would evaluate the possibility to use the leaflet property [maxNativeZoom](http://leafletjs.com/reference-1.2.0.html#gridlayer-maxnativezoom). Maybe it is possible to enable as leaflet is also used under the hoods.
