### ISSUE TITLE
Polygon layer not shown on top of raster layer

### ISSUE THREAD

**Issue by ivanprado** [splashblot/dronedb#66]
Tested locally. 

Steps to reproduce:
* Unzip [that dataset](https://drive.google.com/a/tileo.co/file/d/0B1xeahBrlcA4WjQ4cXJKY2QwcWs/view?usp=sharing)
* Create a map with the raster file
* Upload json layer. Use the "center map on layer" feature to center map on data. 

Different problems/strange behaviors found:
* After doing that you'll see that polygon layer is not shown. 
* Even if raster layer is disabled (clicking on the eye), vector layer is not show. Changing styles doesn't help.
* If you leave the map by clicking on top-left Carto logo and then return to the map, both layers are shown properly. 
* After repeating changing layer visibility and leaving/returning map now vector layer is always behind the raster one. I have repeated that several times but I was not able to return to the case where vector layer is on top. 
* I can see that vector layer is behind raster layer (because of the borders), but If I disable visibility of raster layer nothing is shown. Is like both were disabled.

**Comment by jjmata** [comment]
This seems very similar to the issues Diego reported recently, leaving with @apercas for his comments.

**Comment by ivanprado** [comment]
@apercas just verified that this issue is also present at new deployment of splashblot.tileo.co

**Comment by apercas** [comment]
Please check https://github.com/splashblot/dronedb/pull/69
![image](https://user-images.githubusercontent.com/704210/31198808-d2778fde-a955-11e7-9122-7a630f0246f0.png)

**Comment by ivanprado** [comment]
Results of test on development env after https://github.com/splashblot/dronedb/pull/72

Everything worked well but deleting raster layer. When deleting a raster layer it is still shown. If you leave the map and return, it disappear, which is the expected. So the map at database is right, it is just something at the view.

**Comment by ivanprado** [comment]
State of the bug after the new cartodb.js rebase done by @apercas on October 7 into `tileo/v4` branch:

In general vector layers are shown on top of rasters properly, making the raster feature usable. But still some issues remain:

- [ ] First time you create a map and add the layers, vector layers are below raster layers. The issue disappears when reopening the map.
- [ ] Toggling visibility on raster layer doesn't work. Although visibility is respected when reopening the map. 
- [ ] Toggling visibility when many raster layers doesn't work. It seems to randomly choose one. 
- [ ] Raster deletion is not reflected on viewed map. Reopening the map solves the problem. 
- [ ] Ordering between raster layers is not possible. Although probably that should be cover over a different issue.

**Comment by apercas** [comment]
I think we can close this now that we use a proper way to display raster, reopen if needed
