### ISSUE TITLE
Remove/disable carto logo on maps

### ISSUE THREAD

**Issue by ivanprado** [splashblot/dronedb#68]
Carto logo is shown at bottom center on public and builder maps.

**Comment by jjmata** [comment]
I thought this was taken care of [here](https://github.com/splashblot/docker-dronedb/blob/master/tileo/sampledata/smartrural/setup_smartrural_organization.sh#L26), but it seems like every time we create a user that `feature_flag` needs to be applied to the new user (doesn't seem to inherit from the org.)

See here for an example of a "working" map:
  * https://smartrural.tileo.co/u/smartrural-admin/builder/664494a9-60d5-4a00-8123-d70b0c8edd66/embed?state=%7B%22map%22%3A%7B%22ne%22%3A%5B40.319325896602095%2C-74.68917846679689%5D%2C%22sw%22%3A%5B41.09384217129622%2C-73.34609985351564%5D%2C%22center%22%3A%5B40.707710007867334%2C-74.01763916015626%5D%2C%22zoom%22%3A10%7D%7D

**Comment by jjmata** [comment]
So the action here is to run the `feature_flag` needs to be run on the following accounts in the following two `smartrural` accounts:
  * `fruit-attraction`
  * `datasets`

Done!  Here is an example working: https://smartrural.tileo.co/u/fruit-attraction/builder/5e069f76-e1c4-4274-8b25-7732f40220f9

You probably will have to recreate your previous visualization.

**Comment by ivanprado** [comment]
Map recreated. @jjmata so how can we enable/disable these feature flags? 

Just running `rake cartodb:features:enable_feature_for_organization[disabled_cartodb_logo,$ORGANIZATION_NAME] RAILS_ENV=$RAILS_ENV`on dronedb container?

**Comment by jjmata** [comment]
Yes, that is the only way I know of.  It probably is just a true/flase flag in a table, but the safe way is to run the `rake` command for now.  I will do it everytime a new SSL cert needs to be created (as both things are needed.)  OK?

**Comment by ivanprado** [comment]
Ok, so we can close that issue then.
