### ISSUE TITLE
Extend Carto importer to process tiling of GeoTIFFs

### ISSUE THREAD

**Issue by jjmata** [splashblot/dronedb#7]
Same as https://github.com/splashblot/dronedb/issues/3 but starting with a pre-stitched GeoTIFF (basically do everything we do for unstitched images but skip to the step after stitching has been completed by ODM for people who submit a well-referenced TIFF.)

**Extra credit:** Possibly store assets in S3 per organization if possible!  Parallelize at some point as well, see https://github.com/GitHubRGI/geopackage-python/wiki/Usage-Instructions-for-gdal2tiles_parallel.py

Make sure error conditions are well handled/reported:

  - [ ] File too big (facilitate avoiding the `max_import_file_size` limit restriction)
  - [ ] Lack of `gdal2tiles.py` in path (fix the same for other `gdal*` binaries, please!)
  - [ ] Non-georeferenced TIFFs get loaded but not tiled / they don't error out (and maybe get presented on a non-referenced canvas in the future?)

Test to make sure that orthomosaics generated by the major vendors work:

  - [ ] [Pix4D](https://pix4d.com/product/pix4dmapper-pro/)
  - [ ] [Agisoft Photoscan](http://www.agisoft.com/)
  - [ ] [MapsMadeEasy](https://www.mapsmadeeasy.com/)
  - [ ] Others?

**Comment by jjmata** [comment]
Yes, this means we create a default viz. as with #3 as well.  Everything that we do in #3 that makes sense here, we should also do it with GeoTIFFs that people upload as well.

**Comment by jjmata** [comment]
What is not terribly clear is that we should actually continue uploading the damn TIFFs to PostGIS, but for the time being let's leave it that way.

/cc @javisantana so he doesn't get rid of TIFF imports quite yet or without letting us know first :trollface:

**Comment by jjmata** [comment]
Moving to next milestone.

**Comment by jjmata** [comment]
Once we have #1 working, could we use some of the logic there to help here @apercas?  What I envision is that we import the GeoTIFF into PostGIS and then create a default visualization just like the ones we've been putting on [codepen](http://codepen.io/jjmata/pen/jyaRYZ) - that one only works on Safari due to HTTPS cross-domain requests.

That way we save ourselves having to wait for the tiling (except we do wait for the import/overlays to be created!)

**Comment by jjmata** [comment]
I've started on at least part of this, so taking over for now ...

**Comment by jjmata** [comment]
This is WIP here: https://github.com/splashblot/dronedb/tree/tileo-feature/tiff-tiler

**Comment by jjmata** [comment]
Not critical for April, so moving to next milestone.

**Comment by jjmata** [comment]
Another milestone, another delay.

**Comment by ivanprado** [comment]
I'll close the ticket now that rasters can be imported directly to Postgres without the need external use of tiling
