### ISSUE TITLE
Make the inferences of Quadvine

### ISSUE THREAD

**Issue by amlarraz** [splashblot/dronedb#80]
### Context
*Please explain here below what you were doing when the issue happened*
Make the inferences over all datasets obtained with Quadvine in september 2017 and create visualizations of all these inferences.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Make inferences over: Matarromera, Emilio-moro, Valdemonjas and Pago de Carraovejas
2. Prepare these inferences to create a map in Tileo. (upload to S3, create json file...)
3. Create the map.

### Current Result
*Please describe here below the current result you got*
I've finished the following datasets:

- Matarromera Parcela 3.
- Emilio Moro.

### Expected result
*Please describe here below what should be the expected behaviour*

**Comment by ivanprado** [comment]
@amlarraz could you update the status of that? Regards.

**Comment by amlarraz** [comment]
Everything done. 
Only for have a summary these are the parcelas where we've taken and infered the data:

Pago de Carraovejas Parcela 1
Pago de Carraovejas Parcela 2
Matarromera Parcela 3
Matarromera Parcela 4
Emilio Moro
Valdemonjas

Every inferences have their own map in the specific client account.
