### ISSUE TITLE
On builder: renaming raster layer prevents from rendering

### ISSUE THREAD

**Issue by apercas** [splashblot/dronedb#98]
### Steps to Reproduce
1. Add a raster dataset to a new map
2. Rename the layer (**NOT** the dataset, renaming a dataset does work)
3. Reload

### Current Result
The raster layer doesn't show up

### Expected result
The raster layer should be visible

**Comment by ivanprado** [comment]
Example tile URL before the renaming:
`http://dev.localhost.lan/api/v1/map/93dfd15e6bf9ffbe9f3d3bf1cef8ccf7:1513868105275/1/17/64042/48847.png?api_key=6ad6f49c42239df34a1673decef4e7e9f88962d6`

Example URL after the renaming:

`http://dev.localhost.lan/api/v1/map///17/64043/48850.png?api_key=6ad6f49c42239df34a1673decef4e7e9f88962d6`

Map name, and layers selector are empty.

**Comment by ivanprado** [comment]
It seems that the fix finally was not working. It generated troubles when layer reordering.

**Comment by apercas** [comment]
Update: https://github.com/splashblot/cartodb.js/pull/5/
